listeners:
  default:
    max-connections: 50000
    type: tcp
    bind: 0.0.0.0:8080
timeout-disconnect-delay: 2
auth:
  plugins: ["auth.anonymous"] #List of plugins to activate for authentication among all registered plugins
  allow-anonymous: true
topic-check:
  enabled: true
  plugins: ["topics"]
  topics:
    "anonymous": ["led"]
